-- Importação: Descritores da Matriz de Recomposição (SAEB)
-- Total: 101 descritores | documento='Matriz' tipo='Descritor'
-- Revisado: descrições limpas (OCR multi-coluna corrigido)

INSERT INTO habilidades (codigo, descricao, tipo, documento, disciplina_id, ano_escolar, etapa_ensino, ativo)
VALUES
-- ─── Matemática ─ Anos Iniciais ──────────────────────────────────────────────
('2M1.6',  'Identificar datas, dias da semana ou meses do ano em calendário ou escrever uma data, apresentando o dia, o mês e o ano.', 'Descritor', 'Matriz', 3, '1,2',   'Ensino Fundamental - Anos Iniciais', 1),
('5E1.2',  'Ler, identificar ou comparar dados estatísticos expressos em tabelas.', 'Descritor', 'Matriz', 3, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5E1.6',  'Inferir a finalidade de uma pesquisa estatística ou de um levantamento.', 'Descritor', 'Matriz', 3, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5E2.2',  'Argumentar ou analisar argumentações/conclusões com base nos dados apresentados em tabelas simples ou de dupla entrada ou gráficos (barras, colunas, pictóricos ou de linhas).', 'Descritor', 'Matriz', 3, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5G2.1',  'Descrever ou esboçar o deslocamento de pessoas e/ou de objetos em representações bidimensionais (mapas, croquis etc.) ou plantas de ambientes, de acordo com condições dadas.', 'Descritor', 'Matriz', 3, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5M1.5',  'Identificar horas em relógios analógicos OU associar horas em relógios analógicos e digitais.', 'Descritor', 'Matriz', 3, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5N1.1',  'Escrever números racionais (naturais de até 6 ordens, representação fracionária ou decimal finita até a ordem dos milésimos) em sua representação por algarismos ou em língua materna OU associar o registro numérico ao registro em língua materna.', 'Descritor', 'Matriz', 3, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
-- ─── Língua Portuguesa ─ Anos Iniciais ───────────────────────────────────────
('5LP1.A1', 'Identificar a ideia central do texto.', 'Descritor', 'Matriz', 2, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5LP1.A2', 'Localizar informação explícita.', 'Descritor', 'Matriz', 2, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5LP1.A4', 'Identificar elementos constitutivos de textos narrativos.', 'Descritor', 'Matriz', 2, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5LP1.B6', 'Inferir informações implícitas em textos.', 'Descritor', 'Matriz', 2, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5LP1.B7', 'Inferir o sentido de palavras ou expressões em textos.', 'Descritor', 'Matriz', 2, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
('5LP2.A3', 'Identificar as variedades linguísticas em textos.', 'Descritor', 'Matriz', 2, '3,4,5', 'Ensino Fundamental - Anos Iniciais', 1),
-- ─── Matemática ─ Anos Finais ────────────────────────────────────────────────
('9A1.1',  'Resolver uma equação polinomial de 1º grau.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A1.3',  'Identificar uma representação algébrica para o padrão ou a regularidade de uma sequência.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A1.4',  'Identificar representações algébricas equivalentes.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A1.5',  'Associar uma equação polinomial de 1º grau com duas variáveis a uma reta no plano cartesiano.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A1.6',  'Inferir uma equação polinomial de 2º grau que modela um problema.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A1.7',  'Resolver uma equação polinomial de 2º grau.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A1.8',  'Associar uma das representações de uma função afim ou quadrática a outra de suas representações.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A2.1',  'Resolver problemas que envolvam variação de proporcionalidade direta ou inversa entre duas ou mais grandezas.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A2.2',  'Resolver problemas que envolvam cálculo do valor numérico de expressões algébricas.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A2.3',  'Resolver problemas que possam ser representados por sistema de equações polinomiais de 1º grau.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A2.4',  'Resolver problemas que possam ser representados por equações polinomiais de 2º grau.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9A2.5',  'Resolver problemas que envolvam função afim.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E1.1',  'Identificar os indivíduos (universo ou população-alvo da pesquisa), as variáveis e os dados de uma pesquisa.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E1.2',  'Representar OU associar os dados de uma pesquisa estatística ou de um levantamento por meio de tabela ou gráfico.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E1.3',  'Inferir a finalidade da realização de uma pesquisa estatística ou de um levantamento.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E1.4',  'Interpretar o significado das medidas de tendência central (média aritmética, moda e mediana).', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E1.5',  'Calcular os valores de medidas de tendência central de uma pesquisa ou levantamento.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E2.1',  'Resolver problemas que envolvam dados estatísticos apresentados em tabelas ou gráficos.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E2.2',  'Argumentar OU analisar argumentações/conclusões com base nos dados apresentados em tabelas ou gráficos.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E2.3',  'Explicar/descrever os passos para a realização de uma pesquisa estatística ou de um levantamento.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9E2.4',  'Resolver problemas que envolvam a probabilidade de ocorrência de um evento.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.1',  'Identificar, no plano cartesiano, figuras obtidas por uma ou mais transformações geométricas (reflexão, translação, rotação).', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.2',  'Relacionar o número de vértices, faces ou arestas de prismas ou pirâmides, em função do seu polígono da base.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.3',  'Relacionar objetos tridimensionais às suas planificações ou vistas.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.4',  'Classificar polígonos em regulares e não regulares.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.5',  'Identificar propriedades e relações existentes entre os elementos de um triângulo.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.6',  'Classificar triângulos ou quadriláteros em relação aos lados ou aos ângulos internos.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.7',  'Reconhecer polígonos semelhantes ou as relações existentes entre ângulos e lados correspondentes nesses tipos de polígonos.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.8',  'Reconhecer circunferência/círculo como lugares geométricos, seus elementos e relações.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.9',  'Identificar retas ou segmentos de retas concorrentes, paralelos ou perpendiculares.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G1.10', 'Identificar relações entre ângulos formados por retas paralelas cortadas por uma transversal.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G2.1',  'Descrever OU esboçar o deslocamento de pessoas e/ou de objetos em representações como mapas, croquis e outras.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G2.2',  'Construir/desenhar figuras geométricas planas ou espaciais que satisfaçam condições dadas.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G2.3',  'Resolver problemas que envolvam relações entre ângulos formados por retas paralelas e transversais.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G2.4',  'Resolver problemas que envolvam relações métricas do triângulo retângulo.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G2.5',  'Resolver problemas que envolvam polígonos semelhantes.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G2.6',  'Resolver problemas que envolvam aplicação das relações de proporcionalidade entre figuras semelhantes.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G2.7',  'Resolver problemas que envolvam relações entre os elementos de uma circunferência ou círculo.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9G2.8',  'Determinar o ponto médio de um segmento de reta ou a distância entre dois pontos no plano cartesiano.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9M2.1',  'Resolver problemas que envolvam medidas de grandezas (comprimento, massa, capacidade, temperatura, área, volume).', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9M2.2',  'Resolver problemas que envolvam perímetro de figuras planas.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9M2.3',  'Resolver problemas que envolvam áreas de figuras planas.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9M2.4',  'Resolver problemas que envolvam volume de prismas retos ou cilindros retos.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.1',  'Escrever números racionais (representação fracionária ou decimal finita) em sua representação por algarismos ou em língua materna OU associar o registro numérico ao registro em língua materna.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.2',  'Compor OU decompor números racionais positivos (representação decimal finita) na forma aditiva, ou em suas ordens, ou em adições e multiplicações.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.3',  'Identificar números racionais ou irracionais.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.4',  'Comparar OU ordenar números reais, com ou sem suporte da reta numérica, OU aproximar números reais para múltiplos da potência de 10 mais próxima.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.5',  'Calcular o resultado de adições, subtrações, multiplicações ou divisões envolvendo números racionais.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.6',  'Calcular o resultado de potenciação ou radiciação envolvendo números reais.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.7',  'Representar frações menores ou maiores que a unidade por meio de representações pictóricas OU associar frações a representações pictóricas.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.8',  'Identificar frações equivalentes.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.9',  'Converter uma representação de um número racional positivo para outra representação.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.10', 'Determinar uma fração geratriz para uma dízima periódica.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N1.11', 'Identificar um número natural como primo, composto, múltiplo/fator de ou divisor de OU identificar a decomposição de um número natural em fatores primos OU relacionar as propriedades aritméticas (primo, composto, múltiplo/fator de ou divisor de) de um número natural à sua decomposição em fatores primos.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N2.1',  'Resolver problemas de adição, subtração, multiplicação, divisão, potenciação ou radiciação envolvendo números reais, inclusive notação científica.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N2.2',  'Resolver problemas de contagem cuja resolução envolva a aplicação do princípio multiplicativo.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N2.3',  'Resolver problemas que envolvam porcentagens, incluindo os que lidam com acréscimos e decréscimos simples, aplicação de percentuais sucessivos e determinação das taxas percentuais.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9N2.4',  'Resolver problemas que envolvam as ideias de múltiplo, divisor, máximo divisor comum e mínimo múltiplo comum.', 'Descritor', 'Matriz', 3, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
-- ─── Língua Portuguesa ─ Anos Finais ─────────────────────────────────────────
('9LP1.A1', 'Identificar o uso de recursos persuasivos em textos verbais e não verbais.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.A2', 'Identificar elementos constitutivos de textos pertencentes ao domínio jornalístico-midiático.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.A3', 'Identificar formas de organização de textos normativos, legais e/ou científicos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.A4', 'Identificar teses/opiniões/posicionamentos explícitos e argumentos em textos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.A5', 'Identificar elementos constitutivos de gêneros de divulgação científica.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.A6', 'Identificar a finalidade de textos de diferentes gêneros.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B1', 'Analisar elementos constitutivos de textos pertencentes ao domínio literário.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B2', 'Analisar a intertextualidade entre textos literários ou entre estes e outras linguagens.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B3', 'Inferir a presença de valores sociais, culturais e humanos em textos literários.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B4', 'Analisar efeitos de sentido produzido pelo uso de formas de apropriação de outros textos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B5', 'Inferir informações implícitas em distintos textos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B6', 'Distinguir fatos de opiniões em textos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B7', 'Inferir, em textos multissemióticos, efeitos de humor, ironia e/ou de crítica.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B8', 'Analisar marcas de parcialidade em textos jornalísticos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B9', 'Analisar a relação temática entre diferentes gêneros jornalísticos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.B10','Analisar os efeitos de sentido decorrentes dos mecanismos de construção da narrativa literária.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.C1', 'Avaliar diferentes graus de parcialidade em textos jornalísticos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP1.C2', 'Avaliar a fidedignidade de informações sobre um mesmo fato divulgadas em diferentes fontes.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.A1', 'Identificar os recursos de modalização em textos diversos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.A3', 'Relacionar argumentos às evidências que os sustentam.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.B1', 'Analisar o uso de figuras de linguagem como estratégia argumentativa.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.B2', 'Analisar os efeitos de sentido dos tempos, modos e/ou vozes verbais em textos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.B3', 'Analisar os mecanismos que contribuem para a progressão textual.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.B4', 'Analisar os processos de referenciação lexical e pronominal.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.B5', 'Analisar as variedades linguísticas em textos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.B6', 'Analisar os efeitos de sentido produzidos pelo uso de modalizadores em textos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.C1', 'Avaliar a adequação das variedades linguísticas em contextos de uso.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.C2', 'Avaliar a eficácia das estratégias argumentativas em textos de diferentes gêneros.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP2.C3', 'Avaliar o uso adequado dos verbos modais em contextos diversos.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1),
('9LP3.D1', 'Produzir texto em língua portuguesa, de acordo com o gênero textual e o tema demandados.', 'Descritor', 'Matriz', 2, '6,7,8,9', 'Ensino Fundamental - Anos Finais', 1)
ON DUPLICATE KEY UPDATE
    descricao    = VALUES(descricao),
    ano_escolar  = VALUES(ano_escolar),
    etapa_ensino = VALUES(etapa_ensino),
    ativo        = VALUES(ativo),
    updated_at   = CURRENT_TIMESTAMP;

SELECT h.documento, d.nome AS disciplina, h.ano_escolar, COUNT(*) AS total
FROM habilidades h
LEFT JOIN disciplinas d ON d.id = h.disciplina_id
WHERE h.documento = 'Matriz'
GROUP BY h.documento, d.nome, h.ano_escolar
ORDER BY d.nome, h.ano_escolar;
